version: '3.9'
services:
  webapp:
    build:
      context: .
      dockerfile: ./src/Pulse.WebApp/Dockerfile
    ports:
      - "5000:8080"
    environment:
      RabbitMQ__Host: rabbitmq
      Authentication__Authority: http://host.docker.internal/realms/Pulse
      modules__0__properties__Configuration__Database__ConnectionString: Server=host.docker.internal;Port=5432;Database=pulseposts;User Id=postgres;Password=postgres;"
      modules__1__properties__Configuration__Redis__ConnectionString: host.docker.internal:6379
      modules__2__properties__Configuration__Keycloak__ApiBase: http://host.docker.internal:8080
      modules__3__properties__Configuration__Database__ConnectionString: Server=host.docker.internal;Port=5432;Database=pulsefollowers;User Id=postgres;Password=postgres;
    depends_on: [ "db", "keycloak", "rabbitmq", "redis" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - "8080:8080"
    volumes:
      - ./build/keycloak/realm-export.json:/tmp/realm-export.json
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: PulsePosts,postgres:PulseFollowers,postgres
    ports:
      - "5432:5432"
    volumes:
      - ./build/postgres/scripts:/docker-entrypoint-initdb.d
      - ./data/postgres/data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data
