FROM mcr.microsoft.com/dotnet/sdk:9.0

RUN curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
RUN chmod 500 nsolid_setup_deb.sh
RUN ./nsolid_setup_deb.sh 21
RUN apt-get install nodejs -y
RUN npm install -g tailwindcss

COPY . ./app

WORKDIR /app/src/Pulse.WebApp
CMD ["dotnet", "watch", "--project", "Pulse.WebApp.csproj"]
